
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: false

title: Jong Jae Choi <br>(최정재)
description: __E-mail__ <br>jjchoi at kipf dot re dot kr <br>jongchoi2893 at gmail dot com 
